{"name": "test_api_timeout", "status": "broken", "statusDetails": {"message": "AttributeError: 'RaisesContext' object has no attribute 'raise_for_status'", "trace": "api = <tests.api_client.RickAndMortyAPI object at 0x1043db320>, monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x1044adc70>\n\n    def test_api_timeout(api, monkeypatch):\n        \"\"\"–ü—Ä–æ–≤–µ—Ä—è–µ–º, —á—Ç–æ –ø—Ä–∏ —Ç–∞–π–º–∞—É—Ç–µ –≤–æ–∑–≤—Ä–∞—â–∞–µ—Ç—Å—è —Å–æ–æ—Ç–≤–µ—Ç—Å—Ç–≤—É—é—â–∞—è –æ—à–∏–±–∫–∞\"\"\"\n        monkeypatch.setattr(api.session, \"request\", lambda *args, **kwargs: pytest.raises(Timeout))\n>       response = api.get_character(1)\n\ntests/test_errors.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ntests/api_client.py:57: in get_character\n    return self.request(\"GET\", f\"character/{character_id}\")\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <tests.api_client.RickAndMortyAPI object at 0x1043db320>, method = 'GET', endpoint = 'character/1', params = None, response_model = None, timeout = 5\n\n    def request(\n            self,\n            method: str,\n            endpoint: str,\n            params: Optional[dict] = None,\n            response_model: Optional[Type[BaseModel]] = None,\n            timeout: int = 5\n    ):\n        \"\"\"–û—Ç–ø—Ä–∞–≤–ª—è–µ—Ç –∑–∞–ø—Ä–æ—Å –∫ API, –ª–æ–≥–∏—Ä—É–µ—Ç –∏ –≤–∞–ª–∏–¥–∏—Ä—É–µ—Ç –æ—Ç–≤–µ—Ç\"\"\"\n        url = f\"{self.BASE_URL}/{endpoint}\"\n        logging.info(f\"üì§ –û—Ç–ø—Ä–∞–≤–ª—è–µ–º {method} –∑–∞–ø—Ä–æ—Å –Ω–∞ {url} —Å –ø–∞—Ä–∞–º–µ—Ç—Ä–∞–º–∏ {params}\")\n    \n        try:\n            response = self.session.request(method, url, params=params, timeout=timeout)\n>           response.raise_for_status()  # –ë—Ä–æ—Å–∞–µ—Ç –∏—Å–∫–ª—é—á–µ–Ω–∏–µ –ø—Ä–∏ 4xx/5xx\nE           AttributeError: 'RaisesContext' object has no attribute 'raise_for_status'\n\ntests/api_client.py:30: AttributeError"}, "description": "–ü—Ä–æ–≤–µ—Ä—è–µ–º, —á—Ç–æ –ø—Ä–∏ —Ç–∞–π–º–∞—É—Ç–µ –≤–æ–∑–≤—Ä–∞—â–∞–µ—Ç—Å—è —Å–æ–æ—Ç–≤–µ—Ç—Å—Ç–≤—É—é—â–∞—è –æ—à–∏–±–∫–∞", "start": 1740995513266, "stop": 1740995513266, "uuid": "421228ae-955c-454c-8b9c-c211424f5582", "historyId": "a68d9a9e8d43d090726dead0541fe02f", "testCaseId": "a68d9a9e8d43d090726dead0541fe02f", "fullName": "tests.test_errors#test_api_timeout", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_errors"}, {"name": "host", "value": "MacBook-Pro-Elena.local"}, {"name": "thread", "value": "12031-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_errors"}]}